In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [56]:
df=pd.read_csv('../DATASET/placement.csv')
# x = df.iloc[:, 0].values
# y = df.iloc[:, 1].values
x= df.iloc[:,0:1].values
y= df.iloc[:,-1].values

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=2)

In [59]:
from sklearn.linear_model import LinearRegression

In [60]:
LR = LinearRegression()

In [61]:
LR.fit(x_train,y_train)

LinearRegression()

In [62]:
y_pred = LR.predict(x_test)
y_pred

array([3.89111601, 3.09324469, 2.38464568, 2.57434935, 1.6537286 ,
       1.77647803, 2.07219258, 2.93143862, 3.76278706, 2.93701814,
       4.09197872, 3.51170867, 2.97049525, 2.40138424, 3.18809652,
       3.46707251, 1.94386362, 3.24389172, 2.97607477, 3.41685683,
       2.55761079, 3.16577844, 2.85890486, 3.12114229, 3.68467378,
       2.8700639 , 3.49497011, 3.34432308, 3.91901361, 1.96060218,
       3.65119666, 3.2104146 , 3.74046898, 2.7863711 , 2.78079158,
       3.27178932, 3.52844723, 2.61340599, 2.65804215, 2.71383735])

# LINEAR REGRESSION 

In [63]:
    
class LinearR:
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,x_train,y_train):
        num = 0
        den = 0
        
        for i in range(x_train.shape[0]):
            num = num + (x_train[i] - x_train.mean()) * (y_train[i] - y_train.mean())
            den = den + (x_train[i] - x_train.mean()) ** 2
            
        self.m = num/den
        
        self.b = y_train.mean() - (self.m * x_train.mean())
        
    def predict(self,x_test):
        y_pred = self.m * x_test + self.b
        return y_pred

In [64]:
lr = LinearR()

In [65]:
lr.fit(x_test,y_test)

In [76]:
y_pred = lr.predict(x_test)
y_pred

array([[3.94124514],
       [3.06126684],
       [2.27974766],
       [2.48897327],
       [1.47361369],
       [1.60899497],
       [1.93514077],
       [2.88280971],
       [3.79971017],
       [2.8889634 ],
       [4.16277814],
       [3.52279392],
       [2.92588557],
       [2.29820874],
       [3.16587965],
       [3.47356437],
       [1.7936058 ],
       [3.22741659],
       [2.93203926],
       [3.41818112],
       [2.47051218],
       [3.14126487],
       [2.80281168],
       [3.09203532],
       [3.71355845],
       [2.81511907],
       [3.50433284],
       [3.33818309],
       [3.97201361],
       [1.81206688],
       [3.67663628],
       [3.19049443],
       [3.77509539],
       [2.72281365],
       [2.71665996],
       [3.25818506],
       [3.54125501],
       [2.53204913],
       [2.58127868],
       [2.64281563]])

In [74]:
from sklearn.metrics import r2_score

In [77]:
r2_score(y_test,y_pred)

0.7906534136514854

In [79]:
lr.m

array([0.61536944])

In [80]:
lr.b

array([-1.33862464])

# MULTIPLE LINEAR REGRESSION

In [67]:
class MultipleLR:
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,x_train,y_train):
        x_train = np.insert(x_train,0,1,axis=1)
        
        betas = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)
        
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
        
    def predict(self,x_test):
        y_pred = np.dot(x_test,self.coef_) + self.intercept_
        return y_pred
        
        

In [68]:
ml = MultipleLR()

In [81]:
ml.fit(x_test,y_test)

In [85]:
y_pred = ml.predict(x_test)
y_pred

array([3.94124514, 3.06126684, 2.27974766, 2.48897327, 1.47361369,
       1.60899497, 1.93514077, 2.88280971, 3.79971017, 2.8889634 ,
       4.16277814, 3.52279392, 2.92588557, 2.29820874, 3.16587965,
       3.47356437, 1.7936058 , 3.22741659, 2.93203926, 3.41818112,
       2.47051218, 3.14126487, 2.80281168, 3.09203532, 3.71355845,
       2.81511907, 3.50433284, 3.33818309, 3.97201361, 1.81206688,
       3.67663628, 3.19049443, 3.77509539, 2.72281365, 2.71665996,
       3.25818506, 3.54125501, 2.53204913, 2.58127868, 2.64281563])

In [86]:
r2_score(y_test,y_pred)

0.7906534136514854

In [87]:
ml.coef_

array([0.61536944])

In [88]:
ml.intercept_

-1.3386246406073772

# RESULT OF COMPARISON

In [ ]:
# both give same result for single input and output data
# but for multiple input and output data it is different
# multiple linear regression is more accurate