# NUMPY

In [2]:
# to import numpy
import numpy as np
# np is an alias

In [114]:
my_lst=[1,2,3,4,5]
arr1d=np.array(my_lst)
# creating an array using np.array()

In [116]:
type(arr1d)

numpy.ndarray

In [118]:
arr1d
# one dimensional array

array([1, 2, 3, 4, 5])

In [122]:
# to check whether an array is of which dimension
arr1d.shape

(5,)

In [124]:
# Multinested/Multidimensional array -->
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr2d=np.array([my_lst1,my_lst2,my_lst3])

In [126]:
arr2d

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [128]:
arr2d.shape

(3, 5)

In [130]:
# to recreate the shape of the array(changing rows and colummns)
arr2d.reshape(5,3)
# assigned rows and columns should be equal to the total element otherwisw itll raise error
# if total element 15 then rows and cloms can be only [(15,1)(1,15)(3,5)(5,3)]
# arr.reshape(15,1)
# arr.reshape(1,15)
# arr.reshape(3,5)
# Returns an array containing the same data with a new shape.

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [132]:
arr2d.shape

(3, 5)

## INDEXING

In [60]:
# Accessing the array element in one dimension
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr1[4]

5

In [74]:
# Accessing the array element in two dimension
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2[2]


array([7, 8, 9])

#### Accesing element in two dimensional array -->

In [82]:
# 1. selecting all rows
arr2[:,]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
# 2. selecting all rows and columns
arr2[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
# 3. selectig n rows 
arr2[0:3,]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
# 4. selecting n rows and m columns
arr2[0:3,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [165]:
# Return evenly spaced values within a given interval.
arr=np.arange(0,10)
# arange(start,stop,step(optional))
# arange can be used to quickly form an array

In [167]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
# Return evenly spaced numbers over a specified interval
np.linspace(0,10,50)
# np.linspace(start,stop,num=50,) num is total elements required betwen specified interval

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [179]:
# Copy() function and broadcasting
arr[3:]=100

In [181]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [183]:
arr1=arr

In [185]:
arr1[3:]=100

In [187]:
arr1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [189]:
arr
# changes made in arr1 reflected on arr bcz arr1 and arr shares the same memory space
# because array is referenc type

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [191]:
# to change this we use copy() function
arr1=arr.copy()
# copy() function creates a different memory space 
# Return a copy of the array.

In [197]:
print(arr)
arr1[3:]=500
print(arr1)
# changes does not reflected by using copy()

[  0   1   2 100 100 100 100 100 100 100]
[  0   1   2 500 500 500 500 500 500 500]


### Some conditions that are very useful in Exploratory data Analysis

In [203]:
# 1.
val=2
arr<val
# or we can write it as : arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [205]:
arr*2

array([  0,   2,   4, 200, 200, 200, 200, 200, 200, 200])

In [207]:
arr%2

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [ ]:
# we can perform many conditions on array

In [212]:
# is we require specific element that satisfies the condition then -->
arr[arr<2]

array([0, 1])

In [216]:
arr[arr<100]

array([0, 1, 2])

In [218]:
# 2. Create array and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [220]:
# 3. 
arr1=np.arange(0,10).reshape(5,2)

In [224]:
arr2=np.arange(0,10).reshape(5,2)

In [226]:
arr1*arr2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [228]:
# 4. ones() function can be used to craete an array with replacing all values with 1
np.ones(4)
# 4 is the size of array

array([1., 1., 1., 1.])

In [230]:
# also ones function can be used with dtype
np.ones(4,dtype=int)
# dtype can be used to specify the type of date you required

array([1, 1, 1, 1])

In [232]:
# 5. creating 2D arry in ones function()
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [240]:
# 6. Random distribution
# (A.) rand -->
np.random.rand(3,3)
# random generates random no from 0 to 1 and put in the range specified
# generated no will never be less than 0 and greater than one

array([[0.56485917, 0.51182378, 0.23003477],
       [0.05977815, 0.55760224, 0.22956505],
       [0.01131294, 0.78923   , 0.77849604]])

In [246]:
# (B.) randn -->
arr_ex=np.random.randn(4,4)
arr_ex
# Return a sample (or samples) from the "standard normal" distribution.

array([[-1.18314311,  0.01911645, -0.24728772,  0.17407817],
       [-0.74303178, -0.8987868 ,  0.99427225, -0.51102222],
       [-0.55557612,  1.14597208, -0.14782282, -0.55346496],
       [-0.97389548, -0.45424453, -0.88124059, -0.30922068]])

In [248]:
# (C.) randint -->
np.random.randint(0,100,8).reshape(4,2)
# Return random integers from `low` (inclusive) to `high` (exclusive).
# randint(low, high=None, size=None, dtype=int)

array([[43, 88],
       [33, 56],
       [ 9,  9],
       [25, 42]])

In [250]:
# (D.) random_sample -->
np.random.random_sample((1,5))
# Return random floats in the half-open interval [0.0, 1.0).

array([[0.98182558, 0.46308419, 0.81801441, 0.01168136, 0.50439405]])