In [4]:
import numpy as np
import pandas as pd 

In [5]:
df = pd.read_csv('../../DATASET/train.csv')

In [6]:
df.head()


label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [7]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [8]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

## Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
log = LogisticRegression()

In [11]:
log.fit(X_train,y_train)

c:\Users\godsc\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [12]:
y_pred1 = log.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))

Accuracy of Logistic Regression 0.9145238095238095


In [14]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix



0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

## Descision Tree

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
tre = DecisionTreeClassifier()

In [17]:
tre.fit(X_train,y_train)

DecisionTreeClassifier()

In [18]:
y_pred2 = tre.predict(X_test)

In [19]:

from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Decision Trees 0.854047619047619


In [20]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix



0    1    2    3    4    5    6    7    8    9
0  758    1   10    8    9   14    8    0    9    4
1    1  903    9    7    7    5    5    8   13    4
2    9   17  673   34   17   15   17   23   16    8
3    4   14   26  693    9   49    7   16   27   19
4    7    8   11    5  733   13   13    9   19   38
5   13    5   18   38    9  579   18    8   21   20
6   14    1    8    6   12   20  752    3   17    6
7    3   10   26   17    9    2    1  782    8   15
8   14   12   26   40   17   34   12    4  611   23
9    6    4    7   15   43   18    2   27   22  690

## RECALL , PRECISION , F1 SCORE

In [21]:
from sklearn.metrics import precision_score,recall_score,f1_score

### Calculate Total precision,recall and f1 score

In [ ]:
# Total Precision
precision_score(y_test,y_pred1,average=None)

array([0.94844125, 0.95422177, 0.91411043, 0.90295858, 0.93379791,
       0.8739255 , 0.93262411, 0.91235955, 0.86318408, 0.89320388])

In [ ]:
# Toal Recall
recall_score(y_test,y_pred1,average=None)

array([0.9634592 , 0.97505198, 0.8986731 , 0.88310185, 0.93925234,
       0.83676269, 0.94040524, 0.930126  , 0.87515763, 0.882494  ])

In [ ]:
# Total F1 Score
f1_score(y_test,y_pred1,average=None)

array([0.95589124, 0.96452442, 0.90632603, 0.89291984, 0.93651718,
       0.85494043, 0.93649852, 0.92115712, 0.86912962, 0.88781665])

### To calculate combined value of precision ,recall and f1 score
- 1. Macro
- 2. Weighted

#### MACRO:

In [25]:
# Macro accuracy
precision_score(y_test,y_pred1,average='macro')

0.9128827064397905

In [26]:
# Macro recall
recall_score(y_test,y_pred1,average='macro')

0.9124484028871509

In [27]:
# Macro f1 score
f1_score(y_test,y_pred1,average='macro')

0.9125721045561427

#### WEIGHTED:

In [28]:
# Weighted accuracy
precision_score(y_test,y_pred1,average='weighted')

0.9142150713630827

In [29]:
# Weighted recall
recall_score(y_test,y_pred1,average='weighted')

0.9145238095238095

In [30]:
# Weighted f1 score
f1_score(y_test,y_pred1,average='weighted')

0.9142794994052751

## To Calculate all the metrics at once

In [32]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400

